name = "NashGames"
uuid = "09922fe2-44bb-11ec-0dcf-cd0138771928"
authors = ["Tangi Migot tangi.migot@gmail.com"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"

[compat]
julia = "1"
